# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Philstats
author: Sean Walsh
logo: philstats.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: philstats.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - philstats.bib


# In _config.yml
sphinx:
  config:
    bibtex_reference_style: author_year
    
launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
